# Generated by Django 3.0.6 on 2020-05-23 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QuestionPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='Anonim', max_length=20, verbose_name='username')),
                ('question', models.TextField(max_length=500, verbose_name='question')),
                ('ip', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionPage.QuestionPage')),
            ],
        ),
    ]
