# Generated by Django 3.0.6 on 2020-05-23 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionPage', '0001_initial'),
        ('Question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionPage.QuestionPage', verbose_name='Question Page'),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('status', models.CharField(choices=[('True', 'Liked'), ('False', 'Not Liked')], default='False', max_length=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Question.Question', verbose_name='Question')),
            ],
        ),
    ]
